total_tolles_ferleihsystem/debug_routes/__init__.py
"""
Module containing Debug Methods and sites.

This Module should only be loaded in debug Mode.
"""

from flask import Blueprint, render_template
from .. import APP

if not APP.config['DEBUG']:
    raise ImportWarning("This Module should only be loaded if DEBUG mode is active!")

debug_blueprint = Blueprint('debug_routes', __name__, template_folder='templates',
                            static_folder='static')

from . import routes, debug_db_models


@debug_blueprint.route('/')
@debug_blueprint.route('/index')
def index():
    return render_template('debug/index.html',
                           title='Total Tolles Ferleihsystem – Debug')


APP.register_blueprint(debug_blueprint, url_prefix='/debug')

total_tolles_ferleihsystem/debug_routes/routes.py
import urllib
from flask import render_template, url_for
from .. import APP
from . import debug_blueprint
"""Module containing debug routes index page."""


@debug_blueprint.route('/routes/')
def routes():
    output = []
    for rule in APP.url_map.iter_rules():

        line = {
            'endpoint': rule.endpoint,
            'methods': ', '.join(rule.methods),
            'url': rule.rule
        }
        output.append(line)
    output.sort(key=lambda x: x['url'])
    return render_template('debug/routes/all.html',
                           title='Total Tolles Ferleihsystem – Routes',
                           routes=output)

total_tolles_ferleihsystem/debug_routes/templates/debug/db-models/all.html
<!doctype html>
{% autoescape true %}
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>{{ title }}</title>
    <base href="/">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" type="image/x-icon" href="favicon.ico">
</head>

<body>
    <h1>DB Models overview:</h1>

    <a href="{{url_for('debug_routes.index')}}">back</a>


    <p>DB Models for Data:</p>
    <ul>
        {% for classname in data_classes: %}
        <li><a href="{{url_for('debug_routes.model_detail', classname=classname)}}">{{classname}}</a></li>
        {% endfor %}
    </ul>

</body>

</html>
{% endautoescape %}

total_tolles_ferleihsystem/debug_routes/templates/debug/db-models/model.html
<!doctype html>
{% autoescape true %}
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>{{ title }}</title>
    <base href="/">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" type="image/x-icon" href="favicon.ico">
</head>

<body>
    <h1>DB Model for "{{classname}}":</h1>

    <a href="{{url_for('debug_routes.model_overview')}}">back</a>


    <div>
        <p>Code for fields:</p>
        <code>
            {% for field in model_data['model_fields']: %}
            {{field}}<br />
            {% endfor %}
        </code>
        <p>Normal fields:</p>
        <code>({% for field, class in model_data['normal_attributes']: %}('{{field}}', {{class.__name__}}){%- if not loop.last -%}, {%- endif %}{% endfor %})</code>
        <p>Fields containing lists:</p>
        <code>{{model_data['attributes_containing_lists']}}</code>
        <p>Unknown fields:</p>
        <code>{{model_data['unknown_attributes']}}</code>
    </div>

</body>

</html>
{% endautoescape %}

total_tolles_ferleihsystem/debug_routes/templates/debug/index.html
<!doctype html>
{% autoescape true %}
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>{{ title }}</title>
    <base href="/">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" type="image/x-icon" href="favicon.ico">
</head>

<body>
    <h1>Debug overview:</h1>

    <ul>
        <li><a href="{{url_for('debug_routes.routes')}}">Routes</a></li>
        <li><a href="{{url_for('debug_routes.model_overview')}}">DB Models</a></li>
    </ul>

</body>

</html>
{% endautoescape %}

total_tolles_ferleihsystem/debug_routes/templates/debug/routes/all.html
<!doctype html>
{% autoescape true %}
<html lang="en">

<head>
    <meta charset="utf-8">
    <title>{{ title }}</title>
    <base href="/">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" type="image/x-icon" href="favicon.ico">
</head>

<body>
    <h1>Routes overview:</h1>

    <a href="{{url_for('debug_routes.index')}}">back</a>

    <table>
        <thead>
            <tr>
                <th>URL</th>
                <th>Methods</th>
                <th>Endpoint</th>
            </tr>
        </thead>
        <tbody>
            {% for route in routes: %}
            <tr>
                <td>{{route.url}}</td>
                <td>{{route.methods}}</td>
                <td>{{route.endpoint}}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    <ul>
        {% for tax in taxonomies: %}
        <li><a href="{{url_for('debug_routes.view_taxonomy', taxonomy=tax)}}">{{tax}}</a></li>
        {% endfor %}
    </ul>

</body>

</html>
{% endautoescape %}